<?xml version="1.0" encoding="utf-8"?><Database Name="PizzeriaDB" Class="LinqProductoDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=C:\Users\dafs_\OneDrive\Documentos\PizzeriaDB.mdf;Integrated Security=True;Connect Timeout=30" SettingsObjectName="Caja.Properties.Settings" SettingsPropertyName="PizzeriaDBConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Producto" Member="Producto">
    <Type Name="Producto">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nombre" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="precio" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="cantidad" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>